name: Build Plugin
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - uses: microsoft/setup-msbuild@v1.1
      name: setup-msbuild
      with:
        msbuild-architecture: x64
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore LinksPlugin/LinksPlugin.sln
 
    - name: Build and Publish Web App
      run: msbuild LinksPlugin/LinksPlugin.sln /p:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_plugin
        path: Installer/LinksPlugin.lplug4
