name: Build Plugin
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
     
    - name: Restore NuGet Packages
      run: nuget restore LinksPlugin/LinksPlugin.sln
 
    - name: Build and Publish
      run: msbuild LinksPlugin/LinksPlugin.sln /p:Configuration=Release
 
    - name: Publish GitHub Release Artifacts
      uses: SierraSoftworks/gh-releases@v1.0.6
      with:
        token: secrets.GITHUB_TOKEN
        files: |
         - Installer/LinksPlugin.lplug4
